{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "component-library.serviceAccountName" . }}
  labels:
{{ include "component-library.labels" . | nindent 4 }}
{{- end -}}
