ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/whitelist-source-range: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,81.166.216.225/28

resources:
  limits:
    cpu: 10m
    memory: 100Mi
  requests:
    cpu: 1m
    memory: 30Mi